-- Migration: Add Equipment and Tasks tables

CREATE TABLE IF NOT EXISTS equipment (
    id bigint generated by default as identity primary key,
    company_id bigint references companies(id),
    site_id bigint references sites(id),
    name text not null,
    type text not null, -- 'Excavator', 'Crane', 'Bulldozer'
    status text not null, -- 'operational', 'maintenance', 'critical_failure'
    last_maintenance_date date,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS tasks (
    id bigint generated by default as identity primary key,
    site_id bigint references sites(id),
    name text not null,
    status text not null, -- 'pending', 'in_progress', 'delayed', 'completed'
    start_date date not null,
    end_date date not null,
    depends_on_task_id bigint references tasks(id),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
