export const PERMISSIONS = {
  // Project & Site
  VIEW_PROJECTS: 'VIEW_PROJECTS',
  MANAGE_PROJECTS: 'MANAGE_PROJECTS',
  VIEW_SITES: 'VIEW_SITES',
  MANAGE_SITES: 'MANAGE_SITES',
  
  // Inventory
  VIEW_INVENTORY: 'VIEW_INVENTORY',
  MANAGE_INVENTORY: 'MANAGE_INVENTORY',
  
  // Equipment
  VIEW_EQUIPMENT: 'VIEW_EQUIPMENT',
  MANAGE_EQUIPMENT: 'MANAGE_EQUIPMENT',
  
  // Procurement & Finance
  SUBMIT_MATERIAL_REQUEST: 'SUBMIT_MATERIAL_REQUEST',
  APPROVE_MATERIAL_REQUEST_PM: 'APPROVE_MATERIAL_REQUEST_PM',
  APPROVE_MATERIAL_REQUEST_FINANCE: 'APPROVE_MATERIAL_REQUEST_FINANCE',
  VIEW_FINANCE: 'VIEW_FINANCE',
  MANAGE_FINANCE: 'MANAGE_FINANCE',
  
  // Alerts
  VIEW_ALERTS: 'VIEW_ALERTS',
  RESOLVE_OPERATIONAL_ALERTS: 'RESOLVE_OPERATIONAL_ALERTS',
  RESOLVE_FINANCIAL_ALERTS: 'RESOLVE_FINANCIAL_ALERTS',
  
  // Admin
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_AUDIT_LOG: 'VIEW_AUDIT_LOG',
} as const;

export type Permission = keyof typeof PERMISSIONS;

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  admin: Object.values(PERMISSIONS),
  
  pm: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.VIEW_SITES,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.MANAGE_INVENTORY, // Cross-site transfer etc
    PERMISSIONS.VIEW_EQUIPMENT,
    PERMISSIONS.MANAGE_EQUIPMENT, // Reassigning
    PERMISSIONS.APPROVE_MATERIAL_REQUEST_PM, // PM operational approval
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.RESOLVE_OPERATIONAL_ALERTS,
  ],
  
  contractor: [
    PERMISSIONS.VIEW_PROJECTS, // Scoped to their site only (handled by backend)
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_EQUIPMENT,
    PERMISSIONS.SUBMIT_MATERIAL_REQUEST,
  ],
  
  finance: [
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.VIEW_SITES,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_EQUIPMENT,
    PERMISSIONS.APPROVE_MATERIAL_REQUEST_FINANCE, // Financial approval & POs
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.MANAGE_FINANCE, // Payments
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.RESOLVE_FINANCIAL_ALERTS,
  ]
};

export function hasPermission(userPermissions: Permission[], requiredPermission: Permission): boolean {
  return userPermissions.includes(requiredPermission);
}
